version: '3.9'
services:
  db:
    image: mysql:latest
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: recrutement
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql

  backend-nodejs:
    build: ./api
    container_name: backend
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: root
      DB_database: recrutement
      DB_CONN_LIMIT: 10
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_secret_ACCESS_KEY: ${AWS_secret_ACCESS_KEY}
      AWS_REGION: "us-east-1"
      USER_POOL_ID: "us-east-1_BrylzPIQn"
      USER_POOL_APP_CLIENT_ID: "39rsuvtfgo83c32o8718iuqftg"


    ports:
      - 3000:3000
    volumes:
      - ./api:/app
      
    #depends_on:
    #  - db

  frontend-angular:
    container_name: frontend
    build: ./frontend
    ports:
      - 80:80
  

networks: 
  internal-network:
    driver: bridge